# Copyright 2016-2020 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

dist: xenial

branches:
  only:
    - master
    - develop
    - /feature\/.*/

env:
  matrix:
    - BOGUS_JOB=true

addons:
  apt:
    packages:
      - libopenmpi-dev

matrix:
  exclude:
    - env: BOGUS_JOB=true

  include:

    - env: LIB=random UBP=1 BUILD_SHARED_LIBS=ON
    # - env: LIB=mpi UBP=1 CXXSTD=11

install:
  - BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init --jobs 3 tools/boostdep libs/assert libs/config libs/core libs/$LIB
  - python tools/boostdep/depinst/depinst.py -X test -g "--jobs 3" $LIB
  - rm -rf tools/boost_install/*
  - cp -r $TRAVIS_BUILD_DIR/* tools/boost_install
  - ./bootstrap.sh
  - ./b2 headers
  - if [ -z "$STAGE" ]; then ./b2 -j3 --prefix=$HOME/.local --with-headers ${LAYOUT:+--layout=$LAYOUT} ${TOOLSET:+toolset=$TOOLSET} install; fi
  - pip install --user cmake

script:
  - |-
    echo "using python : 2.7 ;" >> ~/user-config.jam
  - |-
    echo "using python : 3.5 ;" >> ~/user-config.jam
  - |-
    echo "using mpi ;" >> ~/user-config.jam
  - if [ -z "$STAGE" ]; then export B2_INSTALL="--prefix=$HOME/.local install"; fi
  - ./b2 -j3 --with-$LIB ${LAYOUT:+--layout=$LAYOUT} ${STAGEDIR:+--stagedir=$STAGEDIR} ${STAGELIBDIR:+--stage-libdir=$STAGELIBDIR} ${TOOLSET:+toolset=$TOOLSET} ${LINK:+link=$LINK} ${PYTHON:+python=$PYTHON} ${THREADING:+threading=$THREADING} ${CXXSTD:+cxxstd=$CXXSTD} ${B2_INSTALL}
  - cd tools/boost_install/test/$LIB
  - mkdir __build__ && cd __build__
  - if [ -z "$STAGE" ]; then export CMAKE_INSTALL="-DCMAKE_INSTALL_PREFIX=~/.local"; fi
  - cmake ${CMAKE_INSTALL} -DUSE_STAGED_BOOST=${STAGE-0} ${STAGEDIR:+-DBoost_ROOT=$TRAVIS_BUILD_DIR/../boost-root/$STAGEDIR} ${STAGELIBDIR:+-DBoost_ROOT=$TRAVIS_BUILD_DIR/../boost-root/$STAGELIBDIR/cmake} -DUSE_BOOST_PACKAGE=${UBP-0} -DUSE_ALL_COMPONENTS=${USE_ALL_COMPONENTS-0} ${USE_PYTHON_VERSION:+-DUSE_PYTHON_VERSION=$USE_PYTHON_VERSION} ${USE_PYTHON_COMPONENT:+-DUSE_PYTHON_COMPONENT=$USE_PYTHON_COMPONENT} ${BUILD_SHARED_LIBS:+-DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS} -DBoost_VERBOSE=ON ${Boost_USE_STATIC_LIBS:+-DBoost_USE_STATIC_LIBS=$Boost_USE_STATIC_LIBS} ${Boost_COMPILER:+-DBoost_COMPILER=$Boost_COMPILER} ${Boost_USE_MULTITHREADED:+-DBoost_USE_MULTITHREADED=$Boost_USE_MULTITHREADED} ..
  - cmake --build . -v
  - readelf -d liblib.so
  - readelf -d main
  - cmake --build . --target check

notifications:
  email:
    on_success: always
